### ISSUE TITLE
Beautiful site! 

### ISSUE THREAD

**Issue by peterjacobson** [richchurcher/richchurcher.github.io#3]
This is a test Really like kljadf
- need to fix

**Comment by bas-ie** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by bas-ie** [comment]
:heart:
